name: proteosync_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - numpy>=1.24
  - scipy>=1.10
  - pandas>=2.0
  - matplotlib>=3.6
  - seaborn>=0.12
  - plotly>=5.14
  - bokeh>=3.0
  - scikit-learn>=1.3
  - rdkit>=2023.09
  - biopython>=1.81
  - vina>=1.2.5
  - psutil>=5.9
  - pyyaml>=6.0
  - toml>=0.10
  - pytest>=7.0
  - black>=23.0
  - ruff>=0.1
  # CUDA-enabled PyTorch runtime; match to driver if needed
  - pytorch>=2.0
  - torchvision>=0.15
  - torchaudio>=2.0
  - pytorch-cuda>=11.8
  # Molecular dynamics / MD packages (may be heavy to solve)
  - openmm>=8.0
  - pdbfixer>=1.9
  - mdtraj>=1.9
  - openmmforcefields>=0.12
  - pip:
    - pathlib
    - argparse
